### ISSUE TITLE
Post created exception

### ISSUE THREAD

**Issue by DamienVG99** [Radiuscollege/knb#101]
![uhm](https://user-images.githubusercontent.com/31955264/33478577-12288136-d68a-11e7-93e1-c6330eedb46c.png)

**Comment by DamienVG99** [comment]
In the meanwhile, it does create my answer!

**Comment by ricardo1709** [comment]
damien dit is een fout in hun code die een email probeert te sturen.
mijn code voorkomt dat je op een andere pagina komt. zo pagina als toen de search nog niet werkte.

**Comment by ricardo1709** [comment]
flag was op de verkeerde plaats.

**Comment by DamienVG99** [comment]
Mark as closed @Feddman
