### ISSUE TITLE
Laat degene die vraagt om een antwoord de post sluiten wanneer deze is verholpen

### ISSUE THREAD

**Issue by KevinMusters** [Radiuscollege/knb#102]
Wanneer degene die een vraag stelt, het antwoord op de vraag heeft of geen hulp meer nodig heeft, laat hem dan handmatig de post sluiten. Ook heropenen!

**Comment by ricardo1709** [comment]
kevin, dan moet hij zelf het antwoordt op zijn post geven en accepten.
dat was de bedoeling van de docenten waarom je ook op jezelf kan antwoorden.

**Comment by Feddman** [comment]
Thanks voor het meedenken. Graag laten we constructieve posts open, gezien er na een geaccepteerd antwoord nog altijd interessante aanvullingen of betere antwoorden kunnen komen.
