### ISSUE TITLE
House selection system

### ISSUE THREAD

**Issue by luttje** [Radiuscollege/knb#22]
Students bring their laptop on the first day:
- Open selection page
- When all students are ready a teacher initiates the selection
- On the screen of every student their house logo will appear with a fancy animation and perhaps sound

**Comment by svenluijten** [comment]
Were you thinking something with a live connection (over websockets/Pusher) or more of a "refresh your page to see the result" kind of deal? If you want it to happen live, I can recommend [Laravel Echo](https://laravel.com/docs/5.4/broadcasting#installing-laravel-echo).

**Comment by luttje** [comment]
Live would be cool of course. Thanks for the recommendation, I'll have a look at it.

**Comment by svenluijten** [comment]
Echo is lovely. And since [Pusher's pricing](https://pusher.com/pricing) is really not bad at all. For a small app like this, the sandbox plan (free!) would work just fine.
