### ISSUE TITLE
Migrations failing if the "points" table isn't present

### ISSUE THREAD

**Issue by svenluijten** [Radiuscollege/knb#25]
Right now, running the migrations fails if there is no `points` table. Of course, I expect my migrations to create this table, but it can't right now. This is the error I'm getting: 

```
$ php artisan migrate:refresh


  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'knb.POINTS' doesn't exist (SQL: SELECT SUM(`score_types`.`points`) as total, `houses`.`name`
  as name, `houses`.`id` as id
                  FROM `POINTS`
                  INNER JOIN `score_types` ON `score_types`.`id` = `points`.`score_type_id`
                  LEFT JOIN `users` ON `users`.`id` = `points`.`receiver_id`
                  INNER JOIN `house_roles` ON `users`.id = `house_roles`.`user_id`
                  INNER JOIN `houses` ON `house_roles`.`house_id` = `houses`.`id`
                  GROUP BY name, id
                  ORDER BY total DESC
                   LIMIT 4)


  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'knb.POINTS' doesn't exist
```

**Comment by svenluijten** [comment]
This is happening because you're currently relying on a (fully working) database in [your `AppServiceProvider`](https://github.com/Radiuscollege/knb/blob/master/app/Providers/AppServiceProvider.php#L22), which runs during the bootstrapping process of the application. 

The bootstrapping is kicked off by `php artisan`, and before it can migrate the table, it tries to run [this query](https://github.com/Radiuscollege/knb/blob/master/app/House.php#L29-L37), which triggers the error.

We'll need a better (more robust) data model and structure in the app if we want it to work, so this might be worth discussing 🙂

**Comment by Feddman** [comment]
I understand. I need some table data across the website independent of any controllers. I'll look into a more robust solution.

**Comment by svenluijten** [comment]
A good solution for this would be to move this logic outside of the `AppServiceProvider` into your own `ViewServiceProvider` (or similar) and set the public property `$defer` on that provider to `true`. This way the registering / booting of the provider is deferred until a later moment in the app, when you know you have a database connection and everything is set up.

I'm not sure if this works for view composers, but it's worth a shot. 🙂

**Comment by Feddman** [comment]
cfd74239d08534f3cc53550e23e461eb0f76d711
Would this be a feasable solution?

**Comment by svenluijten** [comment]
Does it work? 😄 If so, that'd be a perfect solution. That way, you're splitting the responsibility for the view composers to its own service provider, allowing you to keep all view-related logic contained.

**Comment by Feddman** [comment]
It does! I'm learning so much, thank you so much for your support.
