### ISSUE TITLE
Stop relying on raw SQL queries

### ISSUE THREAD

**Issue by svenluijten** [Radiuscollege/knb#26]
Laravel has a great query builder out of the box ([Eloquent](https://laravel.com/docs/5.4/eloquent)), so there should be no (to little) need to run raw SQL statements like the one [here](https://github.com/Radiuscollege/knb/blob/master/app/House.php#L29-L37) anymore.

**Comment by Feddman** [comment]
Eloquent sometimes slows me down in development,  because the SQL is there right in my mind. I don't think there are any downsides to this?

**Comment by svenluijten** [comment]
Technically not, but it makes sense to make use of the query builder if it's already there. The query builder is also easier to test and change later on.

**Comment by Feddman** [comment]
I'll leave this stuff for optimalisation rounds. (That means, letting my students do the cleanup....)

**Comment by svenluijten** [comment]
Haha, that's fair. I'll also toy around with this to see if there's a better way to do this with Eloquent 👍
