### ISSUE TITLE
stuff to do students

### ISSUE THREAD

**Issue by Feddman** [Radiuscollege/knb#33]
Kobus:
Mobile menu fixen
make other stuff responsive

Dennis:
Extend story line

Kevin:
Sidebar (user ranking filter)

Tim S:
Making a start User profile
Flag post bug on _post.blade.php

Keanu:
komt nog

Lennart: 
Text menu aanpassen

Ronald:
Houdt zich vooral bezig met installatie zelf

Tim Kt:
Nog geen suggesties

Bart:
Begin maken met nieuw ui quiz

Yordi:
denkt er nog over na.

Dominick:
Denkt er nog over na.

**Comment by kobus1998** [comment]
Icons gebruiken in de nav-menu om ruimte te besparen?

- messages = [envelope](http://fontawesome.io/icon/envelope-o/)
- profile = [user](http://fontawesome.io/icon/user/)
- dashboard = [graph](http://fontawesome.io/icon/bar-chart/) (iets in die richting)
- logout = [sign-out](http://fontawesome.io/icon/sign-out/)

Alternatief zou een dropdown met een [cog](http://fontawesome.io/icon/cog/) kunnen zijn.

**Comment by Feddman** [comment]
@kobus1998  

Dit vind ik wel een overzichtelijk geheel (soundcloud).
wat jij?
![image](https://user-images.githubusercontent.com/4361792/27035886-3a7a6d36-4f83-11e7-9c15-c1b0a57fc41a.png)

**Comment by kobus1998** [comment]
@Feddman 

Ja, soundcloud heeft een goede ui, ik ben nu even een codepen aan het maken om te kijken wat de handigste manier is. De header in Bulma is niet zo goed helaas (zoals bij de meeste css frameworks). Daarom schrijf ik meestal zelf een header.

Ik zal kijken of ik een responsive versie van de soundcloud header kan maken.
[Resultaat](https://codepen.io/kobuxz/full/dRMEzm/)
