### ISSUE TITLE
User table migraties conflicteren in vendor.

### ISSUE THREAD

**Issue by kobus1998** [Radiuscollege/knb#45]
In de repo ```studiokaa\amoclient``` heet er ook een migratie ```CreateUsersTable```. Daarom krijg ik nu  deze error bij het uitvoeren van de migraties.
```
[Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot declare class CreateUsersTable, because the name is already in use
```

**Comment by luttje** [comment]
Does the migration get loaded if you change the namespace of that migration class to StudioKaa\Amoclient?

**Comment by kobus1998** [comment]
@TheJjokerR Yup, that fixed it. But had to add
```
Schema::defaultStringLength(191);
```
To the migration in ```studiokaa\amoclient``` and it's missing ```$table->integer('points')->nullable();```.

Besides that, does anyone else get the same error in a empty db?

**Comment by bartjroos** [comment]
Please review readme file at: https://github.com/StudioKaa/amoclient

> Lastly, you should remove any default users-migration from your app, because Amoclient will conflict with it. Do not remove the user-model. If you want to keep using your own migration, in your .env file set: AMO_USE_MIGRATION=no

**Comment by kobus1998** [comment]
@bartjroos Got it, we should add a it to the ```example.env``` to prevent later confusion.
