### ISSUE TITLE
Forum filter op Microsoft Edge

### ISSUE THREAD

**Issue by SabinevdBroek** [Radiuscollege/knb#77]
![image](https://user-images.githubusercontent.com/33345528/32943364-29c6a5ba-cb8c-11e7-88a0-69805fe2e190.png)

**Comment by D257443** [comment]
Why are you even trying this on MS Edge?

**Comment by keanu1997** [comment]
Dit probleem doet zich op meerdere browsers voor.
![afbeelding](https://user-images.githubusercontent.com/16192275/33945267-d323c5ba-e01e-11e7-88fc-c4cd0b4fb76a.png)
