### ISSUE TITLE
Token mismatches

### ISSUE THREAD

**Issue by Feddman** [Radiuscollege/knb#8]
20% of the time I'm getting a token mismatch exception. Any ideas why? caching stuff?

**Comment by svenluijten** [comment]
It seems this is a common issue when using `php artisan serve`. For a more stable development environment, consider installing [Laravel Homestead](https://laravel.com/docs/master/homestead). 

The `php artisan serve` command uses your local installation of PHP, with its own configuration (caching, modules being en- or disabled) and everything. With Homestead (or any virtual machine, really), you can ensure everyone has the same versions of the software installed and it's all configured the same as well.

**Comment by Feddman** [comment]
will try out homestead, thanks.
