### ISSUE TITLE
Add auto-gift badges

### ISSUE THREAD

**Issue by ricardo1709** [Radiuscollege/knb#92]
- [ ] "Overachiever!!" als een cijfer hoger is dan 9 of gelijk aan.
- [ ]  verwijder "Overachiever!!" uit badges request

- [ ] "Always there!" als de persoon altijd aanwezig was.
- [ ]  verwijder "Always there!" uit badges request

- [ ]  "Fashionably on time!" als de persoon nooit te laat was.
- [ ]  verwijder "Fashionably on time!" uit badges request

dit ver komt meer badges request voor simple badges

**Comment by Feddman** [comment]
We haven't connected the system to these activities yet, so we still have to do this manually.
