### ISSUE TITLE
bug search

### ISSUE THREAD

**Issue by ricardo1709** [Radiuscollege/knb#95]
- [x] block reply van search antwoorden
![image](https://user-images.githubusercontent.com/33345530/33327224-45bb909a-d457-11e7-889b-a981d6193105.png)

**Comment by DamienVG99** [comment]
https://hub.amo.rocks/post/search?_token=48fGs8vXiZEmEOCVWcpvmSYI8ni3WT39JaT9B9iH&query=hoe

**Comment by ricardo1709** [comment]
of zie https://hub.amo.rocks/post/482
