### ISSUE TITLE
Filter disables on next page

### ISSUE THREAD

**Issue by KevinMusters** [Radiuscollege/knb#96]
The filter you enabled, disables when you click 'next' or click on an other page number

**Comment by DamienVG99** [comment]
Browser/Client should remember search query. URL doesn't show a page query.

**Comment by Feddman** [comment]
fixed

**Comment by DamienVG99** [comment]
Doesn't work, please reopen @Feddman 
And no, I cleared my cache

**Comment by Feddman** [comment]
works on my machine ;)

**Comment by DamienVG99** [comment]
Hmm... @Feddman still doesn't work here. Already closed for 42 minutes. @KevinMusters is this still a problem for you?

**Comment by D257443** [comment]
I see where this goes wrong!

**Comment by DamienVG99** [comment]
https://youtu.be/g-xddCQoKiM

**Comment by DamienVG99** [comment]
@Feddman

**Comment by Feddman** [comment]
I see know. the ' filter and pagination' combo doesnt work, but the  'search and pagination' does, thanks for clearing that out. will fix soon.

**Comment by DamienVG99** [comment]
Thank you!

**Comment by Feddman** [comment]
fixed now. Test please? 760407d

**Comment by DamienVG99** [comment]
Can be closed @Feddman
